name: CD

on:
  push:
    branches: [main, staging]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/social-badge-fe
            git pull origin ${{ github.ref_name }}
            pnpm install --frozen-lockfile
            pnpm build
            if [ "${{ github.ref_name }}" = "main" ]; then
              pm2 restart social-badge-fe
            else
              pm2 restart social-badge-staging
            fi
